// src/valkit.vue
<template>
  <slot :value="rValue" />
</template>

<script setup lang="ts" generic="T, R">
import { computed } from 'vue'
import type { GetValue, ValueHandler } from './core'
import { valkit } from './core'

const props = defineProps<{
  value: GetValue<T>
  handler: ValueHandler<T, R>
}>()

const rValue = computed(() => valkit(props.value, props.handler))
</script>

// src/valkit-react.tsx
import { useMemo } from 'react'
import type { GetValue, ValueHandler } from './core'
import { valkit } from './core'

type ValkitProps<T, R, C> = {
  value: GetValue<T>
  handler: ValueHandler<T, R>
  render: (value: R) => C
}

export function Valkit<T, R, C>({ value, handler, render }: ValkitProps<T, R, C>) {
  const resolvedValue = useMemo(() => valkit(value, handler), [value, handler])
  return render(resolvedValue)
}
